# Generated by Django 4.2.4 on 2024-01-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResendEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resend_email', models.BooleanField(default=False)),
                ('send_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreviousTriggeredEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lic_data', models.CharField(max_length=25)),
                ('driver_data', models.CharField(max_length=25)),
                ('classs_data', models.CharField(max_length=25)),
                ('locationEvent_data', models.CharField(max_length=25)),
                ('date_data', models.CharField(max_length=25)),
                ('mineshaft_data', models.CharField(max_length=25)),
                ('personalIndex_data', models.CharField(max_length=25)),
                ('classIDX_data', models.CharField(max_length=25)),
                ('et_data', models.CharField(max_length=25)),
                ('underPersonalIDX_data', models.CharField(max_length=25)),
                ('newPersonalIDX_data', models.CharField(max_length=25)),
                ('underClassIDX_data', models.CharField(max_length=25)),
                ('newClassIDX_data', models.CharField(max_length=25)),
                ('index', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emailtriggering.resendemail')),
            ],
        ),
    ]
