# Generated by Django 4.2.4 on 2024-03-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtriggering', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='previoustriggeredemail',
            name='locationEvent_data',
            field=models.CharField(max_length=250),
        ),
    ]
