# Generated by Django 4.2.4 on 2024-01-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=25, verbose_name='Class')),
                ('one_by_four', models.CharField(max_length=25, verbose_name='1/4 Mile')),
                ('one_by_eight', models.CharField(max_length=25, verbose_name='1/8 Mile')),
            ],
        ),
        migrations.CreateModel(
            name='Pdfdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_url', models.URLField(null=True)),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='csv_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sent_emails', models.BooleanField(default=False)),
            ],
        ),
    ]
