# Generated by Django 4.2.4 on 2024-01-04 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_parser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classindex',
            options={'verbose_name': 'Class Index'},
        ),
    ]
