# Generated by Django 4.2.4 on 2024-01-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_parser', '0002_alter_classindex_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classindex',
            options={'verbose_name_plural': 'Class Index'},
        ),
    ]
