# Generated by Django 4.2.4 on 2025-08-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_parser', '0003_alter_classindex_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactorsByAltitude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altitude', models.CharField(blank=True, max_length=30, null=True)),
                ('factor', models.CharField(blank=True, max_length=30, null=True)),
                ('offset', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Altitude,Factor and Offset List',
            },
        ),
        migrations.CreateModel(
            name='PdfForFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_pdf', models.FileField(upload_to='pdf_parser/factor/')),
            ],
            options={
                'verbose_name_plural': 'Upload PDF for altitude details',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_name', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('altitude', models.CharField(blank=True, max_length=250, null=True)),
                ('slet', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'verbose_name_plural': 'Track List',
            },
        ),
        migrations.CreateModel(
            name='TrackDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_doc', models.FileField(upload_to='pdf_parser/tracklist/')),
            ],
            options={
                'verbose_name_plural': 'Upload Docx file for Track details',
            },
        ),
        migrations.AddField(
            model_name='classindex',
            name='power_adder',
            field=models.BooleanField(default=False),
        ),
    ]
