# Generated by Django 4.2.4 on 2024-01-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lic', models.CharField(max_length=25)),
                ('driver', models.CharField(max_length=50)),
                ('classes', models.CharField(max_length=25, verbose_name='Class')),
                ('personal_index', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='NewRaceDriversList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=25)),
                ('lic', models.CharField(blank=True, max_length=25, null=True)),
                ('driver', models.CharField(blank=True, max_length=50, null=True)),
                ('classes', models.CharField(blank=True, max_length=25, null=True, verbose_name='Class')),
                ('index', models.CharField(blank=True, max_length=25, null=True)),
            ],
        ),
    ]
