# Generated by Django 4.2.4 on 2024-02-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newracedriverslist',
            name='session_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
