# Generated by Django 4.2.4 on 2024-05-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_list', '0002_newracedriverslist_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlist',
            name='date',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
