# Generated by Django 4.2.4 on 2024-05-09 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_list', '0003_driverlist_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='newracedriverslist',
            name='updated_index',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
