# Generated by Django 4.2.4 on 2024-06-28 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_list', '0004_newracedriverslist_updated_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdatedIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lic', models.CharField(max_length=25)),
                ('driver', models.CharField(max_length=50)),
                ('classes', models.CharField(max_length=25, verbose_name='Class')),
                ('personal_index', models.CharField(max_length=25)),
            ],
        ),
    ]
