# Generated by Django 4.2.4 on 2024-07-03 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_list', '0005_updatedindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverlist',
            name='date',
        ),
    ]
