"""
Django settings for automailer project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
# from celery.schedules import crontab  

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^z(816c%rnzkbilln0&52quv%zmo8+_rc$s*zj-e%7f6z2$qua'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_cron',
    'pdf_parser',
    'emailtriggering',
    'driver_list',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'automailer.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'mailer')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'automailer.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


PDF_TABLE_NAME = "fyc_pdf_data"


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mailer-db',
        'USER': 'admin',
        'PASSWORD': 'Mailer@2025',
        'HOST': 'localhost',  # Use socket in WSL
        'PORT': '3306',
    }
    # 'default': {
    #     'ENGINE': 'django.db.backends.sqlite3',
    #     'NAME': BASE_DIR / 'db.sqlite3',
    # }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'data')
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


#Mail credintials of Customer io
CORS_ALLOW_ALL_ORIGINS = True

CUSTOMER_IO_API_KEY = '59cf85b52aa81f99729c9ab9e877cfd9'
# CUSTOMER_IO_API_KEY = '9a8f58a415c13530db12c2e38959c916'

#Railtown logs api key

LOGS_API_KEY = 'eyJ1IjoicGNhZWUyODBiZDhlMGFmNGE2YTk2OWQzYWJjZWQzZGFjZTcucmFpbHRvd25sb2dzLmNvbSIsIm8iOiI4YjMxMmMxMy04Mzg5LTRmMzQtYTQzYS0wYzhlYmJkMjMzOTkiLCJwIjoiN2M3ZDY0ZDYtN2U3ZC00YTIxLTg2MzAtZGIxNDQxNzc1OTI4IiwiaCI6IkpkMGp5NVdlc1FMUTBsK043V2VYQlVUR3V4VUNBWDFFTUprNzlldlZpZjA9IiwiZSI6IjI0ZjE5OWQ2LTY3MDItNGQ3NC1hYzczLTk1ZDY4MTM3MTAwZiJ9'



#Cron job

CRON_CLASSES = [
    'pdf_parser.cron.SendAppendedRowsEmailCronJob'
]  



#Pdf url that to be parsed

PDF_URL = "https://www.nhraracer.com/Files/Tech/2019_Personal_CIC.pdf"

CLASS_INDEX_SCRAPING_URL = 'https://www.nhra.net/stats/indexes_comp.html'

#Pages to be included in PDF
PAGE_INCLUDE = "2"

# SESSION_ENGINE = 'django.contrib.sessions.backends.db'  
# SESSION_COOKIE_NAME = 'sessionid'
# SESSION_ENGINE = "django.contrib.sessions.backends.cache"
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True


DATA_UPLOAD_MAX_NUMBER_FIELDS = 10000